spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventoryms
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8087
  servlet:
    context-path: /inventorymanagement
